now you can insert iso's

diff --git a/libvirt-attach-usb b/libvirt-attach-usb
--- a/libvirt-attach-usb
+++ b/libvirt-attach-usb
@@ -1,26 +1,27 @@
 #!/usr/bin/env bash
 
-set -Eeo pipefail
+# Print the usage information.
+USAGE() {
+    SCRIPT_NAME=$(basename "${BASH_SOURCE[0]}")
+    cat <<EOF
+Usage: $SCRIPT_NAME [option]
 
-# Print usage information.
-usage() {
-	printf 'Usage: %s [-h] ["DOMAIN"] ["USB_ID1,USB_ID2..."]\n' "$(basename "${BASH_SOURCE[0]}")"
-	printf '\n'
-	printf 'Script to help you attach or detach USB devices from a running libvirt virtual machine.\n'
-	printf 'They are optional but please respect the order of the parameters "DOMAIN" and "USB_ID".\n'
-	printf 'Make sure virsh, lsusb, fzf, cut, awk, grep, printf, tr, sed, cat and sudo are in your PATH.\n'
-	printf '\n'
-	printf 'Available options:\n'
-	printf '\n'
-	printf -- '-h, --help\t\tPrint this help and exit.\n'
-	printf -- '-l, --list "DOMAIN"\tList USB devices attached to DOMAIN.\n'
-	printf -- '-d, --detach "DOMAIN"\tList and let you pick the one to be detached.\n'
-	exit
+Options:
+  -h, --help                                               Print this help message.
+  -l, --list-usb [DOMAIN]                                  List attached USB devices.
+  -d, --detach-usb [DOMAIN] [USB_ID1,USB_ID2...]           Detach USB device.
+  -a, --attach-usb [DOMAIN] [USB_ID1,USB_ID2...]           Attach USB device.
+  -r, --remove-usb [DOMAIN]				   Remove unavailable USB devices from the domain XML.
+  -u, --list-iso [DOMAIN] [TARGET_DEVICE]                  List attached iso.
+  -i, --insert-iso /path/to/iso [DOMAIN] [TARGET_DEVICE]   Attach iso file.
+  -e, --eject-iso DOMAIN] [TARGET_DEVICE]                  Detach iso file.
+EOF
+    exit 0 
 }
 
-# Check if the required commands are available.
-command_check() {
-	COMMAND_LIST=(fzf virsh sudo cut awk grep printf lsusb tr sed cat)
+# Check if all dependencies are satisfied.
+DEPENDENCIES_CHECK() {
+	COMMAND_LIST=(comm fzf lsusb sudo virsh xmllint)
 	for COMMAND in "${COMMAND_LIST[@]}"; do
 			if ! type -t "$COMMAND" >/dev/null; then
 				MISSING_COMMANDS+=("$COMMAND")
@@ -32,48 +33,51 @@ command_check() {
 	fi
 }
 
-# Authenticate before piping to fzf.
-sudo_init() {
-	sudo -v
-}
-
-# Check if the domain is running or if the domain name matches what virsh knows.
-domain_check() {
-	if ! sudo virsh list --state-running --name | grep -q "$DOMAIN"; then
-		printf "The domain name is incorrect or the machine isn't running.\n" >&2
+# Check if the domain name is correct.
+DOMAIN_CHECK() {
+	if ! sudo virsh list --name --all 2>/dev/null | grep -swq "$DOMAIN" 2>/dev/null; then
+		printf "Domain name %s is incorrect.\n" "$DOMAIN" >&2
 		exit 1
 	fi
 }
 
-# Get domain name from command line input or from a fzf list.
-domain_get() {
+# Get domain from command line/fzf.
+DOMAIN_GET() {
 	if [ -z "$1" ]; then
-		sudo_init
-		DOMAIN=$(sudo virsh list --state-running --name | tr '\n' ' ' | sed 's/ //g' | fzf)
+		DOMAIN_LIST=$(sudo virsh list --name --all 2>/dev/null | sed '/^$/d')
+		DOMAIN=$(printf "%s" "$DOMAIN_LIST" | fzf --header="available libvirt domains")
+		if [[ -z "${DOMAIN}" ]]; then
+			exit 0
+		fi
 	else
 		DOMAIN="$1"
 	fi
-	domain_check
+	DOMAIN_CHECK
 }
 
-# Check if the USB ID matches what lsusb knows.
-usb_check() {
+# Verify if the informed USB ID is correct.
+USB_CHECK() {
 	for USB_DEV_ID in "${USB_ID[@]}"; do
-		if ! lsusb | grep -q "$USB_DEV_ID"; then
+		if ! lsusb | grep -swq "$USB_DEV_ID"; then
 			USB_NOT_FOUND+=("$USB_DEV_ID")
-			printf "USB ID %s is incorrect or not plugged.\n" "${USB_DEV_ID}" >&2
+			printf "Device %s is incorrect or not plugged to the host.\n" "${USB_DEV_ID}" >&2
+		else
+			VALID_USB_ID+=("$USB_DEV_ID")
 		fi
 	done
-	if [ ${#USB_NOT_FOUND[@]} -gt 0 ]; then
-		exit 1
-	fi
 }
 
 # Get USB ID from command line input or from a fzf list.
-usb_get() {
+USB_GET() {
 	if [[ -z "${1}" && -v DOMAIN ]]; then
 		IFS=$'\n'
-		USB=$(lsusb | fzf -m)
+		if [[ -n ${ATTACHED_USB_LIST} ]]; then
+			LSUSB_LIST=$(lsusb)
+			DETTACHED_USB=$(comm -23 <( printf "%b" "${LSUSB_LIST}" | sort ) <( printf "%b" "${ATTACHED_USB_LIST}" | sort ))
+			USB=$(printf "%s" "$DETTACHED_USB" | fzf -m --header="$DOMAIN - available USB devices (Tab/Shift+Tab to select)")
+		else
+			USB="$(lsusb | fzf -m --header="$DOMAIN - available USB devices (Tab/Shift+Tab to select)")"
+		fi
 		unset IFS
 		for USB_DEV in "${USB[@]}"; do
 			# shellcheck disable=SC2207
@@ -85,44 +89,76 @@ usb_get() {
 		read -a USB_ID -r <<< "$USB_ID_LIST"
 		unset IFS
 	fi
-	usb_check
+	USB_CHECK
 }
 
-# Lists USB devices plugged into the specified domain.
-# This function was created by ChatGPT.
-list_usb_devices() {
-	domain_get "$1"
-	domain_check
-
-	local VENDOR_PRODUCT_LIST=()
-
-	# Parse vendorid:productid pairs from dumpxml output
-	while IFS= read -r line; do
-		if [[ $line =~ "vendor id='"(.*)"'/" ]]; then
-			VENDOR="${BASH_REMATCH[1]}"
-		elif [[ $line =~ "product id='"(.*)"'/" ]]; then
-			PRODUCT="${BASH_REMATCH[1]}"
-			VENDOR_PRODUCT_LIST+=("$VENDOR:$PRODUCT")
-		fi
-	done < <(sudo virsh dumpxml "$DOMAIN" | grep -E "<vendor id='|<product id='")
-
-	# Retrieve information for each vendorid:productid pair
-	for VENDOR_PRODUCT in "${VENDOR_PRODUCT_LIST[@]}"; do
-		VENDOR=$(printf "%s" "$VENDOR_PRODUCT" | cut -d':' -f1)
-		PRODUCT=$(printf "%s" "$VENDOR_PRODUCT" | cut -d':' -f2)
-		USB_INFO=$(lsusb -d "$VENDOR:$PRODUCT" 2>/dev/null)
-		if [[ -n $USB_INFO ]]; then
-			printf "%s\n" "$USB_INFO"
+# List attached USB devices.
+LIST_ATTACHED_USB() {
+	if [[ -z "${DOMAIN}" && -z "${ATTACH_MODE}" ]]; then DOMAIN_GET "$1"; fi
+	if [[ -n "$DOMAIN" && -z "${ATTACH_MODE}" ]]; then DOMAIN_CHECK "$1"; fi
+	IFS=','
+	ATTACHED_VENDOR=$(sudo virsh dumpxml "$DOMAIN" | xmllint --xpath "//domain/devices/hostdev[@type='usb']/source/vendor" - 2>/dev/null | grep -oP 'vendor id="\K[^"]+' | tr '\n' ',' | sed '$s/,$/\n/')
+	ATTACHED_PRODUCT=$(sudo virsh dumpxml "$DOMAIN" | xmllint --xpath "//domain/devices/hostdev[@type='usb']/source/product" - 2>/dev/null | grep -oP 'product id="\K[^"]+' | tr '\n' ',' | sed '$s/,$/\n/' 2>/dev/null)
+	read -a VENDOR_ID_LIST -r <<< "$ATTACHED_VENDOR"
+	read -a PRODUCT_ID_LIST -r <<< "$ATTACHED_PRODUCT"
+	unset IFS
+	for i in "${!VENDOR_ID_LIST[@]}"; do
+		if [[ "$(lsusb -d "${VENDOR_ID_LIST[i]}:${PRODUCT_ID_LIST[i]}" 2>/dev/null)" ]]; then
+			ATTACHED_USB_LIST+="$(lsusb -d "${VENDOR_ID_LIST[i]}:${PRODUCT_ID_LIST[i]}" 2>/dev/null)\n"
+		else
+			INVALID_USB+="$(printf "%s:%s" "${VENDOR_ID_LIST[i]}" "${PRODUCT_ID_LIST[i]}"),"
 		fi
 	done
-
-	exit 0
+	if [[ -z "${ATTACH_MODE}" && -z "${CLEAR_USB}" ]]; then
+		printf "%b" "$ATTACHED_USB_LIST"
+		exit 0
+	fi
 }
 
-# Attach USB device to a running libvirt machine.
-attach_usb_device() {
+CLEAR_USB() {
+	CLEAR_USB=1
+	if [[ -z "$DOMAIN" ]]; then DOMAIN_GET "$1"; fi
+	LIST_ATTACHED_USB
+	if [[ -n "${INVALID_USB}" ]]; then
+		INVALID_USB="$(printf "%s" "$INVALID_USB" | sed 's/,$//')"
+		IFS=","
+		read -a INVALID_USB_LIST -r <<< "${INVALID_USB}"
+		unset IFS
+		for USB_DEV_ID in "${INVALID_USB_LIST[@]}"; do
+			VENDOR_ID=$(printf "%s" "${USB_DEV_ID}" | cut -d ':' -f1)
+			PRODUCT_ID=$(printf "%s" "${USB_DEV_ID}" | cut -d ':' -f2)
+                        XML_FILE=$(mktemp)
+                        XML_CONTENT=$(cat <<-EOF
+                        <hostdev mode='subsystem' type='usb' managed='yes'>
+                                <source>
+                                        <vendor id='${VENDOR_ID}'/>
+                                        <product id='${PRODUCT_ID}'/>
+                                </source>
+                        </hostdev>
+			EOF
+                                        )
+                        printf "%s" "$XML_CONTENT" >"$XML_FILE"
+                        VIRSH_ATTACH_OUTPUT=$(sudo virsh detach-device "$DOMAIN" --file "$XML_FILE" --current 2>/dev/null)
+                        case "$VIRSH_ATTACH_OUTPUT" in
+                                *"detached"*)
+                                        printf "Device %s detached succesfully from the domain %s.\n" "$USB_DEV_ID" "$DOMAIN"
+                                        ;;
+			esac
+			rm "$XML_FILE" 2>/dev/null
+		done
+	fi
+	unset CLEAR_USB
+}
+
+# Attach USB device to the specified domain.
+ATTACH_USB() {
+	ATTACH_MODE="1"
+	if [[ -z "$DOMAIN" ]]; then DOMAIN_GET "$1"; fi
+	if [[ -n "$DOMAIN" ]]; then DOMAIN_CHECK "$1"; fi
+	LIST_ATTACHED_USB
+	if [[ "${#USB_ID[@]}" -eq 0 ]]; then USB_GET "$2"; fi
 	if [[ -n "$DOMAIN" && "${#USB_ID[@]}" -gt 0 ]]; then
-		for USB_DEV_ID in "${USB_ID[@]}"; do
+		for USB_DEV_ID in "${VALID_USB_ID[@]}"; do
 			VENDOR_ID=$(printf "%s" "${USB_DEV_ID}" | cut -d ':' -f1)
 			PRODUCT_ID=$(printf "%s" "${USB_DEV_ID}" | cut -d ':' -f2)
 			XML_FILE=$(mktemp)
@@ -136,26 +172,28 @@ attach_usb_device() {
 			EOF
 					)
 			printf "%s" "$XML_CONTENT" >"$XML_FILE"
-			VIRSH_ATTACH_OUTPUT=$(sudo virsh attach-device "$DOMAIN" --file "$XML_FILE" --current 2>/dev/null || sudo virsh detach-device "$DOMAIN" --file "$XML_FILE" --current 2>/dev/null)
+			VIRSH_ATTACH_OUTPUT=$(sudo virsh attach-device "$DOMAIN" --file "$XML_FILE" --current 2>/dev/null)
 			case "$VIRSH_ATTACH_OUTPUT" in
 				*"attached"*)
 					printf "Device %s attached succesfully to the domain %s.\n" "$USB_DEV_ID" "$DOMAIN"
 					;;
-				*"detached"*)
-					printf "Device %s detached succesfully from the domain %s.\n" "$USB_DEV_ID" "$DOMAIN"
-					;;
+				*)
+					printf "Device %s already attached to the domain %s.\n" "$USB_DEV_ID" "$DOMAIN"
 			esac
-			rm "$(mktemp)" 2>/dev/null
+			rm "$XML_FILE" 2>/dev/null
 		done
 	fi
+	unset ATTACH_MODE
 }
 
-detach_usb_device() {
-	domain_get "$1"
-	domain_check
+# Detach USB device to the specified domain.
+DETACH_USB() {
+	if [[ -z "$DOMAIN" ]]; then DOMAIN_GET "$1"; fi
+	if [[ -n "$DOMAIN" ]]; then DOMAIN_CHECK "$1"; fi
 	if [[ -z "${2}" && -v DOMAIN ]]; then
 		IFS=$'\n'
-		USB=$(list_usb_devices "$DOMAIN" | fzf -m)
+		USB=$(LIST_ATTACHED_USB "$DOMAIN" | fzf -m --header="${DOMAIN} - plugged USB devices (Tab/Shift+Tab to select)")
+		if [[ -z ${USB} ]]; then exit; fi
 		unset IFS
 		for USB_DEV in "${USB[@]}"; do
 			# shellcheck disable=SC2207
@@ -167,31 +205,79 @@ detach_usb_device() {
 		read -a USB_ID -r <<< "$USB_ID_LIST"
 		unset IFS
 	fi
-	usb_check
-	attach_usb_device
+	USB_CHECK
+	ATTACH_MODE="1"
+	LIST_ATTACHED_USB
+	if [[ "${#USB_ID[@]}" -eq 0 ]]; then USB_GET "$2"; fi
+	if [[ -n "$DOMAIN" && "${#USB_ID[@]}" -gt 0 ]]; then
+		for USB_DEV_ID in "${VALID_USB_ID[@]}"; do
+			VENDOR_ID=$(printf "%s" "${USB_DEV_ID}" | cut -d ':' -f1)
+			PRODUCT_ID=$(printf "%s" "${USB_DEV_ID}" | cut -d ':' -f2)
+			XML_FILE=$(mktemp)
+			XML_CONTENT=$(cat <<-EOF
+			<hostdev mode='subsystem' type='usb' managed='yes'>
+				<source>
+					<vendor id='0x${VENDOR_ID}'/>
+					<product id='0x${PRODUCT_ID}'/>
+				</source>
+			</hostdev>
+			EOF
+					)
+			printf "%s" "$XML_CONTENT" >"$XML_FILE"
+			VIRSH_ATTACH_OUTPUT=$(sudo virsh detach-device "$DOMAIN" --file "$XML_FILE" --current 2>/dev/null)
+			case "$VIRSH_ATTACH_OUTPUT" in
+				*"detached"*)
+					printf "Device %s detached succesfully from the domain %s.\n" "$USB_DEV_ID" "$DOMAIN"
+					;;
+				*)
+					printf "Device %s already detached from the domain %s.\n" "$USB_DEV_ID" "$DOMAIN"
+			esac
+			rm "$XML_FILE" 2>/dev/null
+		done
+	fi
+	unset ATTACH_MODE
+	exit 0
+}
+
+INSERT_ISO() {
+	if [[ -z "${1}" ]]; then
+		printf "Missing path for the iso file.\n"
+		exit 1
+	fi
+	if [[ -z "${2}" && -z "${DOMAIN}" ]]; then
+		DOMAIN_GET
+	else
+		DOMAIN_CHECK "${2}"
+	fi
+
+	if [[ -z "${3}" ]]; then
+		ISO_TARGET_DEV_LIST=$(sudo virsh dumpxml "${DOMAIN}" | xmllint --xpath "//domain/devices/disk[@device='cdrom']/target[@dev]" - | grep -oP 'dev="\K[^"]+')
+		ISO_TARGET_DEV=$(printf "%s" "${ISO_TARGET_DEV_LIST}" | fzf --header="$DOMAIN - available CDROM devices")
+	else
+		ISO_TARGET_DEV="${3}"
+	fi
+	if [[ -v ISO_TARGET_DEV && -v DOMAIN ]]; then
+		sudo virsh attach-disk "${DOMAIN}" "${1}" "$ISO_TARGET_DEV" --type cdrom --mode readonly
+	fi
 	exit 0
 }
 
 # Call function to check the needed commands.
-command_check
+DEPENDENCIES_CHECK
 
 # Parameter handling.
 while [ $# -gt 0 ]; do
 	case "${1-}" in
-		-h | --help) usage ;;
-		-l | --list) list_usb_devices "$2" ;;
-		-d | --detach) detach_usb_device "$2" "$3" ;;
+		-h | --help) USAGE ;;
+		-l | --list) LIST_ATTACHED_USB "$2" ;;
+		-d | --detach-usb) DETACH_USB "$2" "$3" ;;
+		-a | --attach-usb) ATTACH_USB "$2" "$3" ;;
+		-r | --remove-usb) CLEAR_USB "$2" ;;
+		-u | --list-iso) LIST_INSERTED_ISO "$2" "$3" ;;
+		-i | --insert-iso) INSERT_ISO "$2" "$3" "$4" ;;
+		-e | --eject-iso) EJECT_ISO "$2" "$3" ;;
 		-?*) printf "Unknown option: %s\n" "$1" >&2; exit 1 ;;
 		*) break ;;
 	esac
 	shift
 done
-
-# Get domain name from the first parameter.
-domain_get "$1"
-
-# Get USB ID from the second parameter.
-usb_get "$2"
-
-# Attach USB device to the running libvirt domain.
-attach_usb_device
